CREATE TABLE `accounts` (
    `USERNAME` VARCHAR(255) NOT NULL ,
    `USERIMG` VARCHAR(255) DEFAULT NULL ,
    `PASSWORD` VARCHAR(255) NOT NULL , 
    `NAME` VARCHAR(255) NOT NULL , 
    `EMAIL` VARCHAR(255) NOT NULL , 
    `BIO` VARCHAR(255) NOT NULL DEFAULT "", 
    UNIQUE `USERNAME` (`USERNAME`(255))
) ENGINE = InnoDB;
