CREATE TABLE `posts` (
    `POSTID`    VARCHAR(255) NOT NULL ,
    `PUSERNAME` VARCHAR(255) NOT NULL ,
    `POSTTEXT`  VARCHAR(255) NOT NULL , 
    `IMGURL`    VARCHAR(255) NOT NULL , 
    `PTIME`     VARCHAR(255) NOT NULL , 
    `PDATE`     VARCHAR(255) NOT NULL , 
    `PTAGS`     VARCHAR(255) NOT NULL , 
    `NSFW`      VARCHAR(255) NOT NULL ,
    UNIQUE `POSTID` (`POSTID`(255))
) ENGINE = InnoDB;